# Generated by Django 2.2.6 on 2019-10-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191024_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.UUIDField(null=True),
        ),
    ]
