# Generated by Django 2.2.6 on 2019-10-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
