# Generated by Django 2.2.6 on 2019-10-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191030_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
