# Generated by Django 2.2.6 on 2019-10-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20191031_1546'),
        ('users', '0007_delete_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
