# Generated by Django 2.2.6 on 2019-11-14 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_auto_20191031_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ConversationMembers',
        ),
    ]
